### Create Product (needs Authorization header with Bearer token)
POST http://localhost:3000/api/product/createProduct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODU5YjQ4NDA1NWYzNzhmNTk5NGE4MTgiLCJpYXQiOjE3NTA3MTIzMjYsImV4cCI6MTc1MDcxOTUyNn0.073iGJ5MTTKxrvvb0_KGFohgIBmBdBRZvR0Qtwsnn8o

{
  "title": "Sample Product",
  "description": "This is a sample product",
  "price": 99.99,
  "images": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
  "amount": 10,
  "category": "Elektronika",
  "subCategory": "Smartphones"
}

### Get All Products (with pagination)
GET http://localhost:3000/api/product/products?page=1

### Get products by user (paginated)
GET http://localhost:3000/api/product/userProducts?user=janek&page=1
Content-Type: application/json

###

### Get a single product by ID
GET http://localhost:3000/api/product/userProducts?id=6859c019eb7f9ce1a04dadcb
Content-Type: application/json






### Get products by category name, default page=1, sort by createdAt desc
GET http://localhost:3000/api/product/categoryProducts?category=Elektronika
Content-Type: application/json

###

### Get products by subcategory name only, page 1, sort by createdAt desc
GET http://localhost:3000/api/product/categoryProducts?subCategory=Smartphones&page=1
Content-Type: application/json

###

### Get products by both category and subcategory names, page 1, sort by createdAt desc
GET http://localhost:3000/api/product/categoryProducts?category=Elektronika&subCategory=Smartphones&page=1
Content-Type: application/json

###

### Get products by category name, sorted by price ascending, page 2
GET http://localhost:3000/api/product/categoryProducts?category=Elektronika&page=1&sortBy=price&order=asc
Content-Type: application/json

###

### Get products by user username "janek", sorted by amount descending, page 1
GET http://localhost:3000/api/product/userProducts?user=janek&page=1&sortBy=amount&order=desc
Content-Type: application/json

###

### Get all products, sorted by price descending, page 3
GET http://localhost:3000/api/product/products?page=3&sortBy=price&order=desc
Content-Type: application/json
